### ISSUE TITLE
phpunit

### ISSUE THREAD

**Issue by leonmex** [mageplaza/magento-2-cron-schedule#2]
If you face error in your unit test change:

From snake coding to camelcase PHPUnit\Framework\TestCase; that fix the problem:

use PHPUnit\Framework\TestCase;

and 

class TimetableTest extends TestCase

**Comment by thaimageplaza** [comment]
Thank you for contacting us. 
We will review and update it in the next version.
Please Wait. Thank you very much!

**Comment by JesKingDev** [comment]
@thaimageplaza  This issue is still not solved in the most recent version of the module. As such, running `bin/magento dev:tests:run unit` fails. Can you please provide a timeline for releasing the fix? This PR - https://github.com/mageplaza/magento-2-cron-schedule/pull/1 - has been open for almost 2 years.
